/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tac;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.Timer;

/**
 *
 * @author Eisner Lopez Acevedo
 */
public class tic extends javax.swing.JFrame {

    /**
     * Creates new form tic
     */
    private static int xo = 0, cont = 0, progreso = 0;
    private final ImageIcon x = new ImageIcon(getClass().getResource("X.png"));
    private final ImageIcon o = new ImageIcon(getClass().getResource("O.png"));
    private Timer tiempo;
    
    public tic() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Tic Tac Toe");
        inicioJuego.hide();
        finJuego.hide();
        Juego.hide();
        Home.show();
        lblXO.setIcon(x);
        tiempo=new Timer(25, new Loading());
        tiempo.start();
        btnInicio.setEnabled(false);
    }
    
    //Cargando
    private class Loading implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent e) {
            progreso=loading.getValue();
            if (progreso < 100){
                progreso++;
                loading.setValue(progreso);
            }else{
                tiempo.stop();
                Home.hide();
                inicioJuego.show();
            }
        }
    
}
    //asignar valores a los icones de los botones
    private void setIconXO (JButton btn){
        if (xo == 0 ){
            btn.setIcon(x);
            xo = 1;
            cont++;
            lblXO.setIcon(o);
            btn.setEnabled(false);
            lblJugador.setText(txtJugador2.getText());
        }else{
            btn.setIcon(o);
            xo = 0;
            cont++;
            lblXO.setIcon(x);
            btn.setEnabled(false);
            lblJugador.setText(txtJugador1.getText());
        }
    }
    //limpiar casillas
    private void finJuego(){
        xo=0;
        cont=0;
        Casilla1.setIcon(null);
        Casilla1.setEnabled(true);
        Casilla2.setIcon(null);
        Casilla2.setEnabled(true);
        Casilla3.setIcon(null);
        Casilla3.setEnabled(true);
        Casilla4.setIcon(null);
        Casilla4.setEnabled(true);
        Casilla5.setIcon(null);
        Casilla5.setEnabled(true);
        Casilla6.setIcon(null);
        Casilla6.setEnabled(true);
        Casilla7.setIcon(null);
        Casilla7.setEnabled(true);
        Casilla8.setIcon(null);
        Casilla8.setEnabled(true);
        Casilla9.setIcon(null);
        Casilla9.setEnabled(true);
        lblXO.setIcon(x);
        finJuego.show();
        Juego.hide();
        lblJugador.setText(txtJugador1.getText());
    }
    //Presionar Casillas...
    private void CasillasClick (JButton btn, JButton a1, JButton a2, 
            JButton b1, JButton b2, JButton c1, JButton c2){
        //setIconXO(btn);
        if (btn.getIcon().equals(a1.getIcon())&&btn.getIcon().equals(a2.getIcon()) ||
                btn.getIcon().equals(b1.getIcon())&&btn.getIcon().equals(b2.getIcon())||
                btn.getIcon().equals(c1.getIcon())&&btn.getIcon().equals(c2.getIcon()))
        {
            if (btn.getIcon().equals(x)){
                Ganador.setText(txtJugador1.getText()+" Con X");
            }else{
                Ganador.setText(txtJugador1.getText()+" Con O");
            }
            finJuego();
        }
        Empate();
    }
    //Empate
    private void Empate(){
        if (cont ==9){
            finJuego();
            Ganador.setText("Empate");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Juego = new javax.swing.JPanel();
        panelTablero = new javax.swing.JPanel();
        Casilla1 = new javax.swing.JButton();
        Casilla2 = new javax.swing.JButton();
        Casilla3 = new javax.swing.JButton();
        Casilla4 = new javax.swing.JButton();
        Casilla5 = new javax.swing.JButton();
        Casilla6 = new javax.swing.JButton();
        Casilla7 = new javax.swing.JButton();
        Casilla8 = new javax.swing.JButton();
        Casilla9 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblXO = new javax.swing.JLabel();
        lblJugador = new javax.swing.JLabel();
        btnRjugar = new javax.swing.JButton();
        btnReiniciar = new javax.swing.JButton();
        finJuego = new javax.swing.JPanel();
        Ganador = new javax.swing.JTextField();
        btnRegresar = new javax.swing.JButton();
        btnReStart = new javax.swing.JButton();
        inicioJuego = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtJugador2 = new javax.swing.JTextField();
        txtJugador1 = new javax.swing.JTextField();
        btnInicio = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Home = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        loading = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Juego.setBackground(new java.awt.Color(51, 255, 153));
        Juego.setPreferredSize(new java.awt.Dimension(400, 500));

        panelTablero.setBackground(new java.awt.Color(0, 51, 51));
        panelTablero.setPreferredSize(new java.awt.Dimension(300, 300));
        panelTablero.setLayout(new java.awt.GridLayout(3, 3));

        Casilla1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Casilla1ActionPerformed(evt);
            }
        });
        panelTablero.add(Casilla1);

        Casilla2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Casilla2ActionPerformed(evt);
            }
        });
        panelTablero.add(Casilla2);

        Casilla3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Casilla3ActionPerformed(evt);
            }
        });
        panelTablero.add(Casilla3);

        Casilla4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Casilla4ActionPerformed(evt);
            }
        });
        panelTablero.add(Casilla4);

        Casilla5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Casilla5ActionPerformed(evt);
            }
        });
        panelTablero.add(Casilla5);

        Casilla6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Casilla6ActionPerformed(evt);
            }
        });
        panelTablero.add(Casilla6);

        Casilla7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Casilla7ActionPerformed(evt);
            }
        });
        panelTablero.add(Casilla7);

        Casilla8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Casilla8ActionPerformed(evt);
            }
        });
        panelTablero.add(Casilla8);

        Casilla9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Casilla9ActionPerformed(evt);
            }
        });
        panelTablero.add(Casilla9);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        jLabel1.setFont(new java.awt.Font("sansserif", 3, 36)); // NOI18N
        jLabel1.setText("Turno:");
        jPanel1.add(jLabel1);

        lblXO.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jPanel1.add(lblXO);

        lblJugador.setBackground(new java.awt.Color(0, 51, 51));
        lblJugador.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblJugador.setForeground(new java.awt.Color(0, 51, 51));

        btnRjugar.setText("Re Jugar");
        btnRjugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRjugarActionPerformed(evt);
            }
        });

        btnReiniciar.setText("Reiniciar");
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JuegoLayout = new javax.swing.GroupLayout(Juego);
        Juego.setLayout(JuegoLayout);
        JuegoLayout.setHorizontalGroup(
            JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JuegoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JuegoLayout.createSequentialGroup()
                        .addGroup(JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblJugador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JuegoLayout.createSequentialGroup()
                        .addGap(0, 46, Short.MAX_VALUE)
                        .addGroup(JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JuegoLayout.createSequentialGroup()
                                .addComponent(panelTablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JuegoLayout.createSequentialGroup()
                                .addComponent(btnRjugar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
            .addGroup(JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JuegoLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(btnReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(285, Short.MAX_VALUE)))
        );
        JuegoLayout.setVerticalGroup(
            JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JuegoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(panelTablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(btnRjugar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JuegoLayout.createSequentialGroup()
                    .addContainerGap(453, Short.MAX_VALUE)
                    .addComponent(btnReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(7, 7, 7)))
        );

        getContentPane().add(Juego, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        finJuego.setBackground(new java.awt.Color(255, 255, 0));
        finJuego.setPreferredSize(new java.awt.Dimension(400, 500));

        Ganador.setEditable(false);

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnReStart.setText("Reiniciar Juego");
        btnReStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReStartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout finJuegoLayout = new javax.swing.GroupLayout(finJuego);
        finJuego.setLayout(finJuegoLayout);
        finJuegoLayout.setHorizontalGroup(
            finJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(finJuegoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Ganador)
                .addContainerGap())
            .addGroup(finJuegoLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(finJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnReStart, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        finJuegoLayout.setVerticalGroup(
            finJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, finJuegoLayout.createSequentialGroup()
                .addContainerGap(220, Short.MAX_VALUE)
                .addComponent(Ganador, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReStart, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
        );

        getContentPane().add(finJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        inicioJuego.setBackground(new java.awt.Color(255, 0, 51));
        inicioJuego.setPreferredSize(new java.awt.Dimension(400, 500));

        jLabel2.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel2.setText("Jugador 1");

        jLabel5.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel5.setText("Jugador 2");

        txtJugador2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtJugador2KeyReleased(evt);
            }
        });

        txtJugador1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtJugador1KeyReleased(evt);
            }
        });

        btnInicio.setText("Inicio");
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tac/ttt.gif"))); // NOI18N

        javax.swing.GroupLayout inicioJuegoLayout = new javax.swing.GroupLayout(inicioJuego);
        inicioJuego.setLayout(inicioJuegoLayout);
        inicioJuegoLayout.setHorizontalGroup(
            inicioJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicioJuegoLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(inicioJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtJugador2)
                    .addComponent(txtJugador1)
                    .addComponent(btnInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inicioJuegoLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(64, 64, 64)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        inicioJuegoLayout.setVerticalGroup(
            inicioJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicioJuegoLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        getContentPane().add(inicioJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Home.setBackground(new java.awt.Color(102, 153, 255));
        Home.setPreferredSize(new java.awt.Dimension(400, 500));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tac/ttt.gif"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tac/Tic-Tac-Toe-Game-grey.png"))); // NOI18N

        javax.swing.GroupLayout HomeLayout = new javax.swing.GroupLayout(Home);
        Home.setLayout(HomeLayout);
        HomeLayout.setHorizontalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addGroup(HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HomeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(HomeLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(loading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        HomeLayout.setVerticalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loading, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        getContentPane().add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Casilla4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Casilla4ActionPerformed
        // TODO add your handling code here:
        setIconXO(Casilla4);
        CasillasClick(Casilla4, Casilla1, Casilla7, Casilla7, Casilla1, Casilla5, Casilla6);
    }//GEN-LAST:event_Casilla4ActionPerformed

    private void Casilla3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Casilla3ActionPerformed
        // TODO add your handling code here:
        setIconXO(Casilla3);
        CasillasClick(Casilla3, Casilla6, Casilla9, Casilla5, Casilla7, Casilla2, Casilla1);
    }//GEN-LAST:event_Casilla3ActionPerformed

    private void Casilla1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Casilla1ActionPerformed
        // TODO add your handling code here:
        setIconXO(Casilla1);
        CasillasClick(Casilla1, Casilla2, Casilla3, Casilla5, Casilla9, Casilla4, Casilla7);
    }//GEN-LAST:event_Casilla1ActionPerformed

    private void Casilla2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Casilla2ActionPerformed
        // TODO add your handling code here:
        setIconXO(Casilla2);
        CasillasClick(Casilla2, Casilla1, Casilla3, Casilla3, Casilla1, Casilla5, Casilla8);
    }//GEN-LAST:event_Casilla2ActionPerformed

    private void Casilla5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Casilla5ActionPerformed
        // TODO add your handling code here:
        setIconXO(Casilla5);
        CasillasClick(Casilla5, Casilla2, Casilla6, Casilla1, Casilla9, Casilla4, Casilla6);
        CasillasClick(Casilla5, Casilla2, Casilla6, Casilla1, Casilla9, Casilla7, Casilla3);
    }//GEN-LAST:event_Casilla5ActionPerformed

    private void Casilla6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Casilla6ActionPerformed
        // TODO add your handling code here:
        setIconXO(Casilla6);
        CasillasClick(Casilla6, Casilla3, Casilla9, Casilla4, Casilla5, Casilla9, Casilla3);
    }//GEN-LAST:event_Casilla6ActionPerformed

    private void Casilla7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Casilla7ActionPerformed
        // TODO add your handling code here:
        setIconXO(Casilla7);
        CasillasClick(Casilla7, Casilla4, Casilla1, Casilla5, Casilla3, Casilla8, Casilla9);
    }//GEN-LAST:event_Casilla7ActionPerformed

    private void Casilla8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Casilla8ActionPerformed
        // TODO add your handling code here:
        setIconXO(Casilla8);
        CasillasClick(Casilla8, Casilla7, Casilla9, Casilla9, Casilla7, Casilla5, Casilla2);
    }//GEN-LAST:event_Casilla8ActionPerformed

    private void Casilla9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Casilla9ActionPerformed
        // TODO add your handling code here:
        setIconXO(Casilla9);
        CasillasClick(Casilla9, Casilla8, Casilla7, Casilla5, Casilla1, Casilla3, Casilla6);
    }//GEN-LAST:event_Casilla9ActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        finJuego.hide();
        Juego.show();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        // TODO add your handling code here:
        inicioJuego.hide();
        Juego.show();
        lblJugador.setText(txtJugador1.getText());
    }//GEN-LAST:event_btnInicioActionPerformed

    private void txtJugador1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJugador1KeyReleased
        // TODO add your handling code here:
        if (!"".equals(txtJugador1.getText())&&!"".equals(txtJugador2.getText())){
            btnInicio.setEnabled(true);
        }else{
            btnInicio.setEnabled(false);
        }
    }//GEN-LAST:event_txtJugador1KeyReleased

    private void txtJugador2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJugador2KeyReleased
        // TODO add your handling code here:
        if (!"".equals(txtJugador1.getText())&&!"".equals(txtJugador2.getText())){
            btnInicio.setEnabled(true);
        }else{
            btnInicio.setEnabled(false);
        }
    }//GEN-LAST:event_txtJugador2KeyReleased

    private void btnReStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReStartActionPerformed
        // TODO add your handling code here:
        inicioJuego.show();
        finJuego.hide();
        txtJugador1.setText("");
        txtJugador2.setText("");
        btnInicio.setEnabled(false);
    }//GEN-LAST:event_btnReStartActionPerformed

    private void btnRjugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRjugarActionPerformed
        // TODO add your handling code here:
        finJuego();
        Juego.show();
        finJuego.hide();
    }//GEN-LAST:event_btnRjugarActionPerformed

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        // TODO add your handling code here:
        inicioJuego.show();
        Juego.hide();
        txtJugador1.setText("");
        txtJugador2.setText("");
        btnInicio.setEnabled(false);        
    }//GEN-LAST:event_btnReiniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Casilla1;
    private javax.swing.JButton Casilla2;
    private javax.swing.JButton Casilla3;
    private javax.swing.JButton Casilla4;
    private javax.swing.JButton Casilla5;
    private javax.swing.JButton Casilla6;
    private javax.swing.JButton Casilla7;
    private javax.swing.JButton Casilla8;
    private javax.swing.JButton Casilla9;
    private javax.swing.JTextField Ganador;
    private javax.swing.JPanel Home;
    private javax.swing.JPanel Juego;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnReStart;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JButton btnRjugar;
    private javax.swing.JPanel finJuego;
    private javax.swing.JPanel inicioJuego;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblJugador;
    private javax.swing.JLabel lblXO;
    private javax.swing.JProgressBar loading;
    private javax.swing.JPanel panelTablero;
    private javax.swing.JTextField txtJugador1;
    private javax.swing.JTextField txtJugador2;
    // End of variables declaration//GEN-END:variables
}
